/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_text = 2,
  anon_sym_LBRACE_DOLLAR = 3,
  anon_sym_LBRACE_COLON = 4,
  anon_sym_LBRACE_EQ = 5,
  anon_sym_RBRACE = 6,
  anon_sym_LBRACE = 7,
  aux_sym_tpl_directive_token1 = 8,
  anon_sym_LBRACEif = 9,
  sym_tpl_else = 10,
  anon_sym_LBRACEelseif = 11,
  sym_tpl_endif = 12,
  anon_sym_LBRACEcompare = 13,
  anon_sym_LBRACEvolist = 14,
  anon_sym_LBRACEforeach = 15,
  anon_sym_LBRACEdefault = 16,
  anon_sym_LBRACEswitch = 17,
  anon_sym_LBRACEcase = 18,
  sym_tpl_endswitch = 19,
  anon_sym_LBRACEinclude = 20,
  anon_sym_SLASH_RBRACE = 21,
  anon_sym_PIPE = 22,
  aux_sym_expression_token1 = 23,
  sym_variable = 24,
  aux_sym_function_call_token1 = 25,
  anon_sym_LPAREN = 26,
  anon_sym_COMMA = 27,
  anon_sym_RPAREN = 28,
  sym_source_file = 29,
  sym__element = 30,
  sym_tpl_tag = 31,
  sym_tpl_output = 32,
  sym_tpl_directive = 33,
  sym_tpl_if = 34,
  sym_tpl_elseif = 35,
  sym_tpl_compare = 36,
  sym_tpl_volist = 37,
  sym_tpl_foreach = 38,
  sym_tpl_default = 39,
  sym_tpl_switch = 40,
  sym_tpl_case = 41,
  sym_tpl_include = 42,
  sym_expression = 43,
  sym_function_call = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_function_call_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_text] = "text",
  [anon_sym_LBRACE_DOLLAR] = "{$",
  [anon_sym_LBRACE_COLON] = "{:",
  [anon_sym_LBRACE_EQ] = "{=",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACE] = "{",
  [aux_sym_tpl_directive_token1] = "tpl_directive_token1",
  [anon_sym_LBRACEif] = "{if",
  [sym_tpl_else] = "tpl_else",
  [anon_sym_LBRACEelseif] = "{elseif",
  [sym_tpl_endif] = "tpl_endif",
  [anon_sym_LBRACEcompare] = "{compare",
  [anon_sym_LBRACEvolist] = "{volist",
  [anon_sym_LBRACEforeach] = "{foreach",
  [anon_sym_LBRACEdefault] = "{default",
  [anon_sym_LBRACEswitch] = "{switch",
  [anon_sym_LBRACEcase] = "{case",
  [sym_tpl_endswitch] = "tpl_endswitch",
  [anon_sym_LBRACEinclude] = "{include",
  [anon_sym_SLASH_RBRACE] = "/}",
  [anon_sym_PIPE] = "|",
  [aux_sym_expression_token1] = "expression_token1",
  [sym_variable] = "variable",
  [aux_sym_function_call_token1] = "function_call_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym__element] = "_element",
  [sym_tpl_tag] = "tpl_tag",
  [sym_tpl_output] = "tpl_output",
  [sym_tpl_directive] = "tpl_directive",
  [sym_tpl_if] = "tpl_if",
  [sym_tpl_elseif] = "tpl_elseif",
  [sym_tpl_compare] = "tpl_compare",
  [sym_tpl_volist] = "tpl_volist",
  [sym_tpl_foreach] = "tpl_foreach",
  [sym_tpl_default] = "tpl_default",
  [sym_tpl_switch] = "tpl_switch",
  [sym_tpl_case] = "tpl_case",
  [sym_tpl_include] = "tpl_include",
  [sym_expression] = "expression",
  [sym_function_call] = "function_call",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_text] = sym_text,
  [anon_sym_LBRACE_DOLLAR] = anon_sym_LBRACE_DOLLAR,
  [anon_sym_LBRACE_COLON] = anon_sym_LBRACE_COLON,
  [anon_sym_LBRACE_EQ] = anon_sym_LBRACE_EQ,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [aux_sym_tpl_directive_token1] = aux_sym_tpl_directive_token1,
  [anon_sym_LBRACEif] = anon_sym_LBRACEif,
  [sym_tpl_else] = sym_tpl_else,
  [anon_sym_LBRACEelseif] = anon_sym_LBRACEelseif,
  [sym_tpl_endif] = sym_tpl_endif,
  [anon_sym_LBRACEcompare] = anon_sym_LBRACEcompare,
  [anon_sym_LBRACEvolist] = anon_sym_LBRACEvolist,
  [anon_sym_LBRACEforeach] = anon_sym_LBRACEforeach,
  [anon_sym_LBRACEdefault] = anon_sym_LBRACEdefault,
  [anon_sym_LBRACEswitch] = anon_sym_LBRACEswitch,
  [anon_sym_LBRACEcase] = anon_sym_LBRACEcase,
  [sym_tpl_endswitch] = sym_tpl_endswitch,
  [anon_sym_LBRACEinclude] = anon_sym_LBRACEinclude,
  [anon_sym_SLASH_RBRACE] = anon_sym_SLASH_RBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [aux_sym_expression_token1] = aux_sym_expression_token1,
  [sym_variable] = sym_variable,
  [aux_sym_function_call_token1] = aux_sym_function_call_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym__element] = sym__element,
  [sym_tpl_tag] = sym_tpl_tag,
  [sym_tpl_output] = sym_tpl_output,
  [sym_tpl_directive] = sym_tpl_directive,
  [sym_tpl_if] = sym_tpl_if,
  [sym_tpl_elseif] = sym_tpl_elseif,
  [sym_tpl_compare] = sym_tpl_compare,
  [sym_tpl_volist] = sym_tpl_volist,
  [sym_tpl_foreach] = sym_tpl_foreach,
  [sym_tpl_default] = sym_tpl_default,
  [sym_tpl_switch] = sym_tpl_switch,
  [sym_tpl_case] = sym_tpl_case,
  [sym_tpl_include] = sym_tpl_include,
  [sym_expression] = sym_expression,
  [sym_function_call] = sym_function_call,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tpl_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACEif] = {
    .visible = true,
    .named = false,
  },
  [sym_tpl_else] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACEelseif] = {
    .visible = true,
    .named = false,
  },
  [sym_tpl_endif] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACEcompare] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEvolist] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEforeach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEdefault] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEswitch] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACEcase] = {
    .visible = true,
    .named = false,
  },
  [sym_tpl_endswitch] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACEinclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_function_call_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_tpl_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_output] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_if] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_elseif] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_compare] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_volist] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_foreach] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_default] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_switch] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_case] = {
    .visible = true,
    .named = true,
  },
  [sym_tpl_include] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_cond = 2,
  field_expr = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_cond] = "cond",
  [field_expr] = "expr",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_expr, 1},
  [1] =
    {field_cond, 1},
  [2] =
    {field_args, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(62);
      ADVANCE_MAP(
        '$', 60,
        '(', 143,
        ')', 145,
        ',', 144,
        '/', 56,
        '_', 139,
        '{', 70,
        '|', 85,
        '}', 69,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(113);
      if (lookahead == ')') ADVANCE(146);
      if (lookahead == '_') ADVANCE(111);
      if (lookahead == '{') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(113);
      if (lookahead == '_') ADVANCE(111);
      if (lookahead == '{') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '}') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(43);
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(42);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(76);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(72);
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(7);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(74);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(57);
      END_STATE();
    case 25:
      if (lookahead == 'h') ADVANCE(80);
      END_STATE();
    case 26:
      if (lookahead == 'h') ADVANCE(78);
      END_STATE();
    case 27:
      if (lookahead == 'h') ADVANCE(58);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 31:
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == '}') ADVANCE(73);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(47);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 'm') ADVANCE(40);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 39:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 40:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 44:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(79);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 49:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 51:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 52:
      if (lookahead == 'w') ADVANCE(29);
      END_STATE();
    case 53:
      if (lookahead == 'w') ADVANCE(32);
      END_STATE();
    case 54:
      if (lookahead == '{') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 55:
      if (lookahead == '{') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 56:
      if (lookahead == '}') ADVANCE(84);
      END_STATE();
    case 57:
      if (lookahead == '}') ADVANCE(75);
      END_STATE();
    case 58:
      if (lookahead == '}') ADVANCE(82);
      END_STATE();
    case 59:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 61:
      if (eof) ADVANCE(62);
      if (lookahead == '{') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LBRACE_DOLLAR);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LBRACE_COLON);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LBRACE_EQ);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      ADVANCE_MAP(
        '$', 66,
        '*', 5,
        '/', 28,
        ':', 67,
        '=', 68,
        'c', 6,
        'd', 19,
        'e', 36,
        'f', 38,
        'i', 21,
        's', 52,
        'v', 39,
      );
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_tpl_directive_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_LBRACEif);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_tpl_else);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LBRACEelseif);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_tpl_endif);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LBRACEcompare);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LBRACEvolist);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_LBRACEforeach);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LBRACEdefault);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_LBRACEswitch);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LBRACEcase);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_tpl_endswitch);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LBRACEinclude);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_SLASH_RBRACE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == '$') ADVANCE(113);
      if (lookahead == ')') ADVANCE(146);
      if (lookahead == '_') ADVANCE(111);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == '$') ADVANCE(113);
      if (lookahead == '_') ADVANCE(111);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == '.') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'A') ADVANCE(91);
      if (lookahead == 'M') ADVANCE(101);
      if (lookahead == 'P') ADVANCE(108);
      if (lookahead == 'R') ADVANCE(104);
      if (lookahead == 'U') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'B') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'C') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'C') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'D') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'E') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'I') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'I') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'L') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'L') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'L') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'N') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'O') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'O') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'O') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'O') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'R') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'T') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'T') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'U') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == 'U') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == '_') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == '_') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead == '_') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(114);
      if (lookahead != 0 &&
          (lookahead < 'a' || '{' < lookahead) &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_expression_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(116);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'A') ADVANCE(120);
      if (lookahead == 'M') ADVANCE(130);
      if (lookahead == 'P') ADVANCE(137);
      if (lookahead == 'R') ADVANCE(133);
      if (lookahead == 'U') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'B') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'C') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'C') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'D') ADVANCE(138);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'E') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'I') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'I') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'L') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'L') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'L') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'N') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'O') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'O') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'O') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'O') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'R') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'T') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'T') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'U') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == 'U') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == '_') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == '_') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (lookahead == '_') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_function_call_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(142);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(115);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 61},
  [2] = {.lex_state = 61},
  [3] = {.lex_state = 61},
  [4] = {.lex_state = 61},
  [5] = {.lex_state = 61},
  [6] = {.lex_state = 61},
  [7] = {.lex_state = 61},
  [8] = {.lex_state = 61},
  [9] = {.lex_state = 61},
  [10] = {.lex_state = 61},
  [11] = {.lex_state = 61},
  [12] = {.lex_state = 61},
  [13] = {.lex_state = 61},
  [14] = {.lex_state = 61},
  [15] = {.lex_state = 61},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 54},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 55},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LBRACE_DOLLAR] = ACTIONS(1),
    [anon_sym_LBRACE_COLON] = ACTIONS(1),
    [anon_sym_LBRACE_EQ] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_LBRACEif] = ACTIONS(1),
    [sym_tpl_else] = ACTIONS(1),
    [anon_sym_LBRACEelseif] = ACTIONS(1),
    [sym_tpl_endif] = ACTIONS(1),
    [anon_sym_LBRACEcompare] = ACTIONS(1),
    [anon_sym_LBRACEvolist] = ACTIONS(1),
    [anon_sym_LBRACEforeach] = ACTIONS(1),
    [anon_sym_LBRACEdefault] = ACTIONS(1),
    [anon_sym_LBRACEswitch] = ACTIONS(1),
    [anon_sym_LBRACEcase] = ACTIONS(1),
    [sym_tpl_endswitch] = ACTIONS(1),
    [anon_sym_LBRACEinclude] = ACTIONS(1),
    [anon_sym_SLASH_RBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [aux_sym_function_call_token1] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym__element] = STATE(2),
    [sym_tpl_tag] = STATE(2),
    [sym_tpl_output] = STATE(2),
    [sym_tpl_directive] = STATE(2),
    [sym_tpl_if] = STATE(15),
    [sym_tpl_elseif] = STATE(15),
    [sym_tpl_compare] = STATE(15),
    [sym_tpl_volist] = STATE(15),
    [sym_tpl_foreach] = STATE(15),
    [sym_tpl_default] = STATE(15),
    [sym_tpl_switch] = STATE(15),
    [sym_tpl_case] = STATE(15),
    [sym_tpl_include] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_text] = ACTIONS(9),
    [anon_sym_LBRACE_DOLLAR] = ACTIONS(11),
    [anon_sym_LBRACE_COLON] = ACTIONS(11),
    [anon_sym_LBRACE_EQ] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACEif] = ACTIONS(15),
    [sym_tpl_else] = ACTIONS(17),
    [anon_sym_LBRACEelseif] = ACTIONS(19),
    [sym_tpl_endif] = ACTIONS(17),
    [anon_sym_LBRACEcompare] = ACTIONS(21),
    [anon_sym_LBRACEvolist] = ACTIONS(23),
    [anon_sym_LBRACEforeach] = ACTIONS(25),
    [anon_sym_LBRACEdefault] = ACTIONS(27),
    [anon_sym_LBRACEswitch] = ACTIONS(29),
    [anon_sym_LBRACEcase] = ACTIONS(31),
    [sym_tpl_endswitch] = ACTIONS(17),
    [anon_sym_LBRACEinclude] = ACTIONS(33),
  },
  [STATE(2)] = {
    [sym__element] = STATE(3),
    [sym_tpl_tag] = STATE(3),
    [sym_tpl_output] = STATE(3),
    [sym_tpl_directive] = STATE(3),
    [sym_tpl_if] = STATE(15),
    [sym_tpl_elseif] = STATE(15),
    [sym_tpl_compare] = STATE(15),
    [sym_tpl_volist] = STATE(15),
    [sym_tpl_foreach] = STATE(15),
    [sym_tpl_default] = STATE(15),
    [sym_tpl_switch] = STATE(15),
    [sym_tpl_case] = STATE(15),
    [sym_tpl_include] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_comment] = ACTIONS(37),
    [sym_text] = ACTIONS(39),
    [anon_sym_LBRACE_DOLLAR] = ACTIONS(11),
    [anon_sym_LBRACE_COLON] = ACTIONS(11),
    [anon_sym_LBRACE_EQ] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_LBRACEif] = ACTIONS(15),
    [sym_tpl_else] = ACTIONS(17),
    [anon_sym_LBRACEelseif] = ACTIONS(19),
    [sym_tpl_endif] = ACTIONS(17),
    [anon_sym_LBRACEcompare] = ACTIONS(21),
    [anon_sym_LBRACEvolist] = ACTIONS(23),
    [anon_sym_LBRACEforeach] = ACTIONS(25),
    [anon_sym_LBRACEdefault] = ACTIONS(27),
    [anon_sym_LBRACEswitch] = ACTIONS(29),
    [anon_sym_LBRACEcase] = ACTIONS(31),
    [sym_tpl_endswitch] = ACTIONS(17),
    [anon_sym_LBRACEinclude] = ACTIONS(33),
  },
  [STATE(3)] = {
    [sym__element] = STATE(3),
    [sym_tpl_tag] = STATE(3),
    [sym_tpl_output] = STATE(3),
    [sym_tpl_directive] = STATE(3),
    [sym_tpl_if] = STATE(15),
    [sym_tpl_elseif] = STATE(15),
    [sym_tpl_compare] = STATE(15),
    [sym_tpl_volist] = STATE(15),
    [sym_tpl_foreach] = STATE(15),
    [sym_tpl_default] = STATE(15),
    [sym_tpl_switch] = STATE(15),
    [sym_tpl_case] = STATE(15),
    [sym_tpl_include] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_comment] = ACTIONS(43),
    [sym_text] = ACTIONS(46),
    [anon_sym_LBRACE_DOLLAR] = ACTIONS(49),
    [anon_sym_LBRACE_COLON] = ACTIONS(49),
    [anon_sym_LBRACE_EQ] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(52),
    [anon_sym_LBRACEif] = ACTIONS(55),
    [sym_tpl_else] = ACTIONS(58),
    [anon_sym_LBRACEelseif] = ACTIONS(61),
    [sym_tpl_endif] = ACTIONS(58),
    [anon_sym_LBRACEcompare] = ACTIONS(64),
    [anon_sym_LBRACEvolist] = ACTIONS(67),
    [anon_sym_LBRACEforeach] = ACTIONS(70),
    [anon_sym_LBRACEdefault] = ACTIONS(73),
    [anon_sym_LBRACEswitch] = ACTIONS(76),
    [anon_sym_LBRACEcase] = ACTIONS(79),
    [sym_tpl_endswitch] = ACTIONS(58),
    [anon_sym_LBRACEinclude] = ACTIONS(82),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(87), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [24] = 2,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(91), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [48] = 2,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(95), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [72] = 2,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(99), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [96] = 2,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(103), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [120] = 2,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(107), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [144] = 2,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(111), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [168] = 2,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(115), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [192] = 2,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(119), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [216] = 2,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(123), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [240] = 2,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(127), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [264] = 2,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(131), 17,
      sym_comment,
      anon_sym_LBRACE_DOLLAR,
      anon_sym_LBRACE_COLON,
      anon_sym_LBRACE_EQ,
      anon_sym_LBRACE,
      anon_sym_LBRACEif,
      sym_tpl_else,
      anon_sym_LBRACEelseif,
      sym_tpl_endif,
      anon_sym_LBRACEcompare,
      anon_sym_LBRACEvolist,
      anon_sym_LBRACEforeach,
      anon_sym_LBRACEdefault,
      anon_sym_LBRACEswitch,
      anon_sym_LBRACEcase,
      sym_tpl_endswitch,
      anon_sym_LBRACEinclude,
  [288] = 7,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(135), 1,
      aux_sym_expression_token1,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      sym_function_call,
    STATE(35), 1,
      sym_expression,
  [310] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(53), 1,
      sym_expression,
  [329] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(42), 1,
      sym_expression,
  [348] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(50), 1,
      sym_expression,
  [367] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(52), 1,
      sym_expression,
  [386] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(41), 1,
      sym_expression,
  [405] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(44), 1,
      sym_expression,
  [424] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(43), 1,
      sym_expression,
  [443] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(51), 1,
      sym_expression,
  [462] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(46), 1,
      sym_expression,
  [481] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(47), 1,
      sym_expression,
  [500] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(40), 1,
      sym_expression,
  [519] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(145), 4,
      anon_sym_RBRACE,
      anon_sym_SLASH_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [532] = 6,
    ACTIONS(133), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_variable,
    ACTIONS(139), 1,
      aux_sym_function_call_token1,
    ACTIONS(143), 1,
      aux_sym_expression_token1,
    STATE(33), 1,
      sym_function_call,
    STATE(39), 1,
      sym_expression,
  [551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 4,
      anon_sym_RBRACE,
      anon_sym_SLASH_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [561] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 4,
      anon_sym_RBRACE,
      anon_sym_SLASH_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [571] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 4,
      anon_sym_RBRACE,
      anon_sym_SLASH_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [581] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 4,
      anon_sym_RBRACE,
      anon_sym_SLASH_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [591] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 4,
      anon_sym_RBRACE,
      anon_sym_SLASH_RBRACE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [601] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      aux_sym_function_call_repeat1,
  [614] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym_function_call_repeat1,
  [627] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym_function_call_repeat1,
  [640] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      aux_sym_function_call_token1,
    STATE(31), 1,
      sym_function_call,
  [650] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [658] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
  [665] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
  [672] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
  [679] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
  [686] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
  [693] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
  [700] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
  [707] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_SLASH_RBRACE,
  [714] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_tpl_directive_token1,
  [721] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_LPAREN,
  [728] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
  [735] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
  [742] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
  [749] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 24,
  [SMALL_STATE(6)] = 48,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 96,
  [SMALL_STATE(9)] = 120,
  [SMALL_STATE(10)] = 144,
  [SMALL_STATE(11)] = 168,
  [SMALL_STATE(12)] = 192,
  [SMALL_STATE(13)] = 216,
  [SMALL_STATE(14)] = 240,
  [SMALL_STATE(15)] = 264,
  [SMALL_STATE(16)] = 288,
  [SMALL_STATE(17)] = 310,
  [SMALL_STATE(18)] = 329,
  [SMALL_STATE(19)] = 348,
  [SMALL_STATE(20)] = 367,
  [SMALL_STATE(21)] = 386,
  [SMALL_STATE(22)] = 405,
  [SMALL_STATE(23)] = 424,
  [SMALL_STATE(24)] = 443,
  [SMALL_STATE(25)] = 462,
  [SMALL_STATE(26)] = 481,
  [SMALL_STATE(27)] = 500,
  [SMALL_STATE(28)] = 519,
  [SMALL_STATE(29)] = 532,
  [SMALL_STATE(30)] = 551,
  [SMALL_STATE(31)] = 561,
  [SMALL_STATE(32)] = 571,
  [SMALL_STATE(33)] = 581,
  [SMALL_STATE(34)] = 591,
  [SMALL_STATE(35)] = 601,
  [SMALL_STATE(36)] = 614,
  [SMALL_STATE(37)] = 627,
  [SMALL_STATE(38)] = 640,
  [SMALL_STATE(39)] = 650,
  [SMALL_STATE(40)] = 658,
  [SMALL_STATE(41)] = 665,
  [SMALL_STATE(42)] = 672,
  [SMALL_STATE(43)] = 679,
  [SMALL_STATE(44)] = 686,
  [SMALL_STATE(45)] = 693,
  [SMALL_STATE(46)] = 700,
  [SMALL_STATE(47)] = 707,
  [SMALL_STATE(48)] = 714,
  [SMALL_STATE(49)] = 721,
  [SMALL_STATE(50)] = 728,
  [SMALL_STATE(51)] = 735,
  [SMALL_STATE(52)] = 742,
  [SMALL_STATE(53)] = 749,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_case, 3, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_case, 3, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_directive, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_directive, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_output, 3, 0, 1),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_output, 3, 0, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_if, 3, 0, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_if, 3, 0, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_elseif, 3, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_elseif, 3, 0, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_compare, 3, 0, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_compare, 3, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_volist, 3, 0, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_volist, 3, 0, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_foreach, 3, 0, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_foreach, 3, 0, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_default, 3, 0, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_default, 3, 0, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_switch, 3, 0, 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_switch, 3, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_include, 3, 0, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_include, 3, 0, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tpl_tag, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tpl_tag, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [180] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tpl5(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tpl5",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
